---
title: Experiments with Spotify Music Features
author: R. Leyshon
date: today
---


```{r}
#| warning: false
library(here)
library(spotifyr)
library(ggplot2)
library(ggridges)
library(dplyr)
library(tidyr)
library(glue)
library(extrafont)
source(here("R/config_secrets.R"))
```

```{r}
config_secrets(here(".git_ignore/secrets.toml"))
access_token <- get_spotify_access_token()
```


```{r}
# get album
album = get_album("6mS0ssCxtLvB0IcVP7sR66")
# get artist name for title
artist_name = album[["artists"]]$name
# collect features for each track in album
tracks = album[["tracks"]]
track_ids = tracks$items$id
track_features = data.frame()
track_names = tracks$items$name
i = 1
for(id in track_ids) {
  track = get_track_audio_features(id)
  track = cbind(track_name = track_names[i], track_order = i, track)
  track_features = rbind(track_features, track)
  i = i + 1
}
# pivot long on features to plot
interest_feats = c("danceability", "energy", "speechiness",
                   "acousticness", "instrumentalness", "valence")
tracks_long = pivot_longer(track_features, cols=all_of(interest_feats), names_to="features")
```


```{r}
#| warning: false

ggplot(tracks_long, aes(x = value, y = features, fill = features)) +
  geom_density_ridges(alpha=0.7, scale = 3, rel_min_height = 0.01) + 
  theme_ridges(grid = FALSE, center_axis_labels = TRUE) +
  ggtitle(
    glue("{album$name} by {artist_name}"),
    subtitle = "A Density Ridge Plot of Audio Features.") +
  labs(x = "", y = "") +
  theme(
    legend.position = "none",
    axis.text.x = element_blank(),
    axis.ticks = element_blank(),
    panel.background = element_rect(fill = "black"),
    plot.background = element_rect(fill = "black"),
    plot.title = element_text(
      color = "white", family = "Arial Rounded MT Bold", size = 14, hjust = 0.5
      ),
    plot.subtitle = element_text(
      color = "white", family = "Arial Rounded MT Bold", size = 10, hjust = 0.5
      ),
    axis.text.y = element_text(
      color = "white", family = "Arial Rounded MT Bold"
      )
    ) 

```


```{r}
# return url of high res album cover art for blog post
album[["images"]][["url"]][1] #1 is highest available res

```