# Example cofiguration file
# make your own replacing the <REPLACE> values
# save as credentials/credentials.toml
[spotify]
client_id = "<replace with your client ID>"
client_secret = "<replace with your client secret>"